-- Emergency Medicine Finder - Complete Database Setup with Sample Data
-- Run this script to set up the database and seed it with realistic sample data
-- Safe to run multiple times - always starts fresh

CREATE DATABASE IF NOT EXISTS emergency_medicine;
USE emergency_medicine;

-- Drop existing tables in reverse dependency order (clean slate)
DROP TABLE IF EXISTS stock_transfer;
DROP TABLE IF EXISTS medicine_request;
DROP TABLE IF EXISTS shopmedicine;
DROP TABLE IF EXISTS worker;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS medicine;
DROP TABLE IF EXISTS org_service;
DROP TABLE IF EXISTS admin;

-- ============================
-- TABLE STRUCTURES
-- ============================

-- Users/Patients table
CREATE TABLE IF NOT EXISTS users (
    u_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) NOT NULL,
    propic VARCHAR(255),
    house VARCHAR(100),
    road VARCHAR(100),
    division VARCHAR(100),
    zila VARCHAR(100),
    upazila VARCHAR(100),
    pass VARCHAR(255) NOT NULL,
    status TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Worker/Shopkeeper table
CREATE TABLE IF NOT EXISTS worker (
    w_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    shopname VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) NOT NULL,
    propic VARCHAR(255),
    nid1 VARCHAR(255),
    nid2 VARCHAR(255),
    house VARCHAR(100),
    road VARCHAR(100),
    division VARCHAR(100),
    zila VARCHAR(100),
    upazila VARCHAR(100),
    lat DECIMAL(10, 8),
    lng DECIMAL(11, 8),
    pass VARCHAR(255) NOT NULL,
    status TINYINT DEFAULT 0,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Master medicine catalog
CREATE TABLE IF NOT EXISTS medicine (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100),
    strength VARCHAR(100),
    generic VARCHAR(255),
    company VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Shop-specific medicine inventory
CREATE TABLE IF NOT EXISTS shopmedicine (
    id INT AUTO_INCREMENT PRIMARY KEY,
    shop_email VARCHAR(255) NOT NULL,
    mediname VARCHAR(255) NOT NULL,
    meditype VARCHAR(100),
    medistrength VARCHAR(100),
    medigeneric VARCHAR(255),
    medicompany VARCHAR(255),
    stock INT DEFAULT 0,
    price DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shop_email) REFERENCES worker(email) ON DELETE CASCADE
);

-- Medicine requests from users
CREATE TABLE IF NOT EXISTS medicine_request (
    req_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    medi_id INT NOT NULL,
    medi_name VARCHAR(255) NOT NULL,
    shop_email VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    ppic VARCHAR(255),
    status TINYINT DEFAULT 0 COMMENT '0: pending, 1: approved, 2: on hold',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE,
    FOREIGN KEY (shop_email) REFERENCES worker(email) ON DELETE CASCADE
);

-- Organization services
CREATE TABLE IF NOT EXISTS org_service (
    ser_id INT AUTO_INCREMENT PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admin accounts
CREATE TABLE IF NOT EXISTS admin (
    admin_id INT AUTO_INCREMENT PRIMARY KEY,
    admin_uid VARCHAR(255) UNIQUE NOT NULL,
    pass VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stock transfer requests from admin to shops
CREATE TABLE IF NOT EXISTS stock_transfer (
    transfer_id INT AUTO_INCREMENT PRIMARY KEY,
    from_shop_email VARCHAR(255) NOT NULL,
    to_shop_email VARCHAR(255) NOT NULL,
    medicine_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    requested_by VARCHAR(255) NOT NULL COMMENT 'admin email',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (from_shop_email) REFERENCES worker(email) ON DELETE CASCADE,
    FOREIGN KEY (to_shop_email) REFERENCES worker(email) ON DELETE CASCADE
);

-- ============================
-- SAMPLE DATA
-- ============================

-- Admin account (password: admin123)
-- Hash generated by bcryptjs with 10 rounds
INSERT IGNORE INTO admin (admin_uid, pass) VALUES
('admin@emf.com', '$2a$10$RhFx78qMA8Fa2IXyukD4oeUwOUCDq7y551/m0bPJqvf8OWPXCJ0m6');

-- Organization services
INSERT IGNORE INTO org_service (service_name, description) VALUES
('Medicine Delivery', 'Emergency medicine delivery service within 30 minutes'),
('Medical Consultation', 'Online medical consultation with licensed physicians'),
('Lab Test Collection', 'Home lab test sample collection service'),
('Vaccination Service', 'Home vaccination service for all age groups'),
('Medical Equipment Rental', 'Rental of medical equipment like oxygen cylinders, wheelchairs');

-- Master Medicine Catalog (50 common Bangladeshi medicines)
INSERT IGNORE INTO medicine (name, type, strength, generic, company) VALUES
('Napa', 'Tablet', '500mg', 'Paracetamol', 'Beximco Pharmaceuticals'),
('Napa Extra', 'Tablet', '500mg + 65mg', 'Paracetamol + Caffeine', 'Beximco Pharmaceuticals'),
('Ace Plus', 'Tablet', '500mg + 65mg', 'Paracetamol + Caffeine', 'Square Pharmaceuticals'),
('Fexo', 'Tablet', '120mg', 'Fexofenadine', 'Square Pharmaceuticals'),
('Tufnil', 'Tablet', '10mg', 'Cetirizine', 'Incepta Pharmaceuticals'),
('Monirol', 'Sachet', '5.6g', 'Methylin', 'Square Pharmaceuticals'),
('Seclo', 'Capsule', '20mg', 'Omeprazole', 'Healthcare Pharmaceuticals'),
('Maxpro', 'Tablet', '40mg', 'Pantoprazole', 'Square Pharmaceuticals'),
('Flagyl', 'Tablet', '400mg', 'Metronidazole', 'ACI Limited'),
('Ciprocin', 'Tablet', '500mg', 'Ciprofloxacin', 'Square Pharmaceuticals'),
('Azithro', 'Tablet', '500mg', 'Azithromycin', 'Square Pharmaceuticals'),
('Cef-3', 'Capsule', '250mg', 'Cefixime', 'Incepta Pharmaceuticals'),
('Moxacil', 'Capsule', '500mg', 'Amoxicillin', 'Beximco Pharmaceuticals'),
('Clavox', 'Tablet', '625mg', 'Amoxicillin + Clavulanic Acid', 'Square Pharmaceuticals'),
('Rancept', 'Tablet', '40mg', 'Rosuvastatin', 'Square Pharmaceuticals'),
('Cardivas', 'Tablet', '6.25mg', 'Carvedilol', 'Square Pharmaceuticals'),
('Angilock', 'Tablet', '50mg', 'Losartan', 'Square Pharmaceuticals'),
('Nebicard', 'Tablet', '5mg', 'Nebivolol', 'Square Pharmaceuticals'),
('Insulatard', 'Injection', '100IU/ml', 'Human Insulin', 'Novo Nordisk'),
('Metformin', 'Tablet', '500mg', 'Metformin', 'Square Pharmaceuticals'),
('Euglucon', 'Tablet', '5mg', 'Glibenclamide', 'ACI Limited'),
('Glipizide', 'Tablet', '5mg', 'Glipizide', 'Beximco Pharmaceuticals'),
('Diapride', 'Tablet', '50mg', 'Vildagliptin', 'Square Pharmaceuticals'),
('Piozon', 'Tablet', '15mg', 'Pioglitazone', 'Square Pharmaceuticals'),
('Alatrol', 'Tablet', '10mg', 'Loratadine', 'Incepta Pharmaceuticals'),
('Histacin', 'Tablet', '10mg', 'Cetirizine', 'Square Pharmaceuticals'),
('Zantic', 'Tablet', '150mg', 'Ranitidine', 'Beximco Pharmaceuticals'),
('Maxpro XL', 'Tablet', '40mg', 'Pantoprazole', 'Square Pharmaceuticals'),
('Domperon', 'Tablet', '10mg', 'Domperidone', 'Incepta Pharmaceuticals'),
('Buscopan', 'Tablet', '10mg', 'Hyoscine Butylbromide', 'ACI Limited'),
('Diclofenac', 'Gel', '1%', 'Diclofenac', 'Square Pharmaceuticals'),
('Voltarol', 'Tablet', '50mg', 'Diclofenac', 'ACI Limited'),
('Ibuprofen', 'Tablet', '400mg', 'Ibuprofen', 'Beximco Pharmaceuticals'),
('Naproxen', 'Tablet', '500mg', 'Naproxen', 'Renata Limited'),
('Maxicet', 'Tablet', '500mg', 'Paracetamol', 'ACI Limited'),
('Oradol', 'Lozenges', '2mg', 'Amylmetacresol', 'Square Pharmaceuticals'),
('Strepsils', 'Lozenges', '1.2mg', 'Dichlorobenzyl Alcohol', 'Reckitt Benckiser'),
('Salbutamol', 'Inhaler', '100mcg', 'Salbutamol', 'Beximco Pharmaceuticals'),
('Budesonide', 'Inhaler', '200mcg', 'Budesonide', 'Square Pharmaceuticals'),
('Montair', 'Tablet', '10mg', 'Montelukast', 'Square Pharmaceuticals'),
('Prednisolone', 'Tablet', '5mg', 'Prednisolone', 'ACI Limited'),
('Dexamethasone', 'Tablet', '0.5mg', 'Dexamethasone', 'Square Pharmaceuticals'),
('Thyrox', 'Tablet', '50mcg', 'Levothyroxine', 'Beximco Pharmaceuticals'),
('Carbagyl', 'Tablet', '200mg', 'Carbamazepine', 'Incepta Pharmaceuticals'),
('Phenobarb', 'Tablet', '30mg', 'Phenobarbital', 'ACI Limited'),
('Diazepam', 'Tablet', '5mg', 'Diazepam', 'Square Pharmaceuticals'),
('Oradexon', 'Tablet', '0.5mg', 'Dexamethasone', 'Renata Limited'),
('Doxacin', 'Capsule', '100mg', 'Doxycycline', 'Square Pharmaceuticals'),
('Claricin', 'Tablet', '500mg', 'Clarithromycin', 'Beximco Pharmaceuticals'),
('Sporilin', 'Capsule', '100mg', 'Itraconazole', 'Square Pharmaceuticals');

-- Sample Users (3 users, all active with status=1)
-- Passwords are bcrypt hashes of "user123"
INSERT IGNORE INTO users (first_name, last_name, gender, email, phone, propic, house, road, division, zila, upazila, pass, status) VALUES
('Rahim', 'Miah', 'Male', 'rahim@email.com', '01711111111', 'default-user.png', '12/A', 'Road 5', 'Dhaka', 'Dhaka', 'Mirpur', '$2a$10$wzweneMmiQg6N5Uxn8mvqupWQSxYxljdvsuCtwiEZw.ELAaRYdYfi', 1),
('Fatima', 'Begum', 'Female', 'fatima@email.com', '01722222222', 'default-user.png', '45', 'Road 12', 'Chattogram', 'Chattogram', 'Halishahar', '$2a$10$wzweneMmiQg6N5Uxn8mvqupWQSxYxljdvsuCtwiEZw.ELAaRYdYfi', 1),
('Karim', 'Hossain', 'Male', 'karim@email.com', '01733333333', 'default-user.png', '78', 'Road 3', 'Dhaka', 'Gazipur', 'Tongi', '$2a$10$wzweneMmiQg6N5Uxn8mvqupWQSxYxljdvsuCtwiEZw.ELAaRYdYfi', 1);

-- Sample Workers/Shopkeepers (3 shops, all active with status=1)
-- Passwords are bcrypt hashes of "worker123"
INSERT IGNORE INTO worker (first_name, last_name, gender, shopname, email, phone, propic, nid1, nid2, house, road, division, zila, upazila, lat, lng, pass, status) VALUES
('Abdul', 'Haque', 'Male', 'Haques Pharmacy', 'haque@pharmacy.com', '01811111111', 'default-shop.png', 'nid1.jpg', 'nid2.jpg', '23', 'Road 8', 'Dhaka', 'Dhaka', 'Mirpur-12', '23.8223', '90.3669', '$2a$10$l.R3r2XEZ84E6LLi1PJyCegnyjGZXqImQOI0B7idYZOtaSJ2TIIKS', 1),
('Shahida', 'Akter', 'Female', 'Shahida Medical Store', 'shahida@medical.com', '01822222222', 'default-shop.png', 'nid1.jpg', 'nid2.jpg', '56', 'Road 15', 'Chattogram', 'Chattogram', 'Agrabad', '22.3192', '91.8041', '$2a$10$l.R3r2XEZ84E6LLi1PJyCegnyjGZXqImQOI0B7idYZOtaSJ2TIIKS', 1),
('Jahangir', 'Alam', 'Male', 'Alam Brothers Pharma', 'alam@pharma.com', '01833333333', 'default-shop.png', 'nid1.jpg', 'nid2.jpg', '12', 'Road 4', 'Dhaka', 'Dhaka', 'Uttara', '23.8763', '90.3796', '$2a$10$l.R3r2XEZ84E6LLi1PJyCegnyjGZXqImQOI0B7idYZOtaSJ2TIIKS', 1);

-- Sample Shop Medicine Inventory
INSERT IGNORE INTO shopmedicine (shop_email, mediname, meditype, medistrength, medigeneric, medicompany, stock, price) VALUES
-- Haque's Pharmacy inventory
('haque@pharmacy.com', 'Napa', 'Tablet', '500mg', 'Paracetamol', 'Beximco', 200, 5.00),
('haque@pharmacy.com', 'Seclo', 'Capsule', '20mg', 'Omeprazole', 'Healthcare', 150, 8.00),
('haque@pharmacy.com', 'Fexo', 'Tablet', '120mg', 'Fexofenadine', 'Square', 100, 6.00),
('haque@pharmacy.com', 'Flagyl', 'Tablet', '400mg', 'Metronidazole', 'ACI', 180, 4.00),
('haque@pharmacy.com', 'Azithro', 'Tablet', '500mg', 'Azithromycin', 'Square', 80, 15.00),
('haque@pharmacy.com', 'Maxpro', 'Tablet', '40mg', 'Pantoprazole', 'Square', 120, 10.00),
('haque@pharmacy.com', 'Moxacil', 'Capsule', '500mg', 'Amoxicillin', 'Beximco', 200, 7.00),
('haque@pharmacy.com', 'Ciprocin', 'Tablet', '500mg', 'Ciprofloxacin', 'Square', 90, 8.00),

-- Shahida Medical Store inventory
('shahida@medical.com', 'Napa', 'Tablet', '500mg', 'Paracetamol', 'Beximco', 300, 4.00),
('shahida@medical.com', 'Zantic', 'Tablet', '150mg', 'Ranitidine', 'Beximco', 100, 5.00),
('shahida@medical.com', 'Alatrol', 'Tablet', '10mg', 'Loratadine', 'Incepta', 80, 3.00),
('shahida@medical.com', 'Ibuprofen', 'Tablet', '400mg', 'Ibuprofen', 'Beximco', 150, 6.00),
('shahida@medical.com', 'Cef-3', 'Capsule', '250mg', 'Cefixime', 'Incepta', 60, 20.00),
('shahida@medical.com', 'Diclofenac', 'Gel', '1%', 'Diclofenac', 'Square', 50, 25.00),
('shahida@medical.com', 'Buscopan', 'Tablet', '10mg', 'Hyoscine', 'ACI', 100, 4.00),
('shahida@medical.com', 'Metformin', 'Tablet', '500mg', 'Metformin', 'Square', 200, 3.00),

-- Alam Brothers Pharma inventory
('alam@pharma.com', 'Napa', 'Tablet', '500mg', 'Paracetamol', 'Beximco', 250, 5.00),
('alam@pharma.com', 'Clavox', 'Tablet', '625mg', 'Amoxicillin+Clavulanate', 'Square', 70, 25.00),
('alam@pharma.com', 'Rancept', 'Tablet', '40mg', 'Rosuvastatin', 'Square', 100, 12.00),
('alam@pharma.com', 'Montair', 'Tablet', '10mg', 'Montelukast', 'Square', 90, 8.00),
('alam@pharma.com', 'Salbutamol', 'Inhaler', '100mcg', 'Salbutamol', 'Beximco', 30, 150.00),
('alam@pharma.com', 'Nebicard', 'Tablet', '5mg', 'Nebivolol', 'Square', 80, 10.00),
('alam@pharma.com', 'Doxacin', 'Capsule', '100mg', 'Doxycycline', 'Square', 100, 6.00),
('alam@pharma.com', 'Claricin', 'Tablet', '500mg', 'Clarithromycin', 'Beximco', 75, 18.00);

-- Sample Medicine Requests
INSERT IGNORE INTO medicine_request (user_id, user_email, medi_id, medi_name, shop_email, quantity, ppic, status) VALUES
(1, 'rahim@email.com', 1, 'Napa', 'haque@pharmacy.com', 20, 'prescription1.jpg', 1),
(1, 'rahim@email.com', 6, 'Maxpro', 'haque@pharmacy.com', 10, 'prescription2.jpg', 0),
(2, 'fatima@email.com', 4, 'Flagyl', 'shahida@medical.com', 15, 'prescription3.jpg', 1),
(2, 'fatima@email.com', 13, 'Cef-3', 'shahida@medical.com', 8, 'prescription4.jpg', 0),
(3, 'karim@email.com', 17, 'Clavox', 'alam@pharma.com', 12, 'prescription5.jpg', 2),
(3, 'karim@email.com', 21, 'Salbutamol', 'alam@pharma.com', 2, 'prescription6.jpg', 0);

-- ============================
-- INDEXES
-- ============================
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_worker_email ON worker(email);
CREATE INDEX idx_medicine_request_user ON medicine_request(user_email);
CREATE INDEX idx_medicine_request_shop ON medicine_request(shop_email);
CREATE INDEX idx_shopmedicine_shop ON shopmedicine(shop_email);

-- ============================
-- VERIFICATION
-- ============================
SELECT 'Database setup complete!' AS message;
SELECT COUNT(*) AS total_users FROM users;
SELECT COUNT(*) AS total_workers FROM worker;
SELECT COUNT(*) AS total_medicines FROM medicine;
SELECT COUNT(*) AS total_shop_inventory FROM shopmedicine;
SELECT COUNT(*) AS total_requests FROM medicine_request;
SHOW TABLES;
